# Generated by Django 3.0 on 2019-12-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField()),
                ('text', models.TextField()),
                ('time', models.DateTimeField()),
                ('stars', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
